In [59]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns

df = pd.read_csv('energydata.csv')
df.head

<bound method NDFrame.head of                       date  Appliances  lights         T1       RH_1  \
0      2016-01-11 17:00:00          60      30  19.890000  47.596667
1      2016-01-11 17:10:00          60      30  19.890000  46.693333
2      2016-01-11 17:20:00          50      30  19.890000  46.300000
3      2016-01-11 17:30:00          50      40  19.890000  46.066667
4      2016-01-11 17:40:00          60      40  19.890000  46.333333
...                    ...         ...     ...        ...        ...
19730  2016-05-27 17:20:00         100       0  25.566667  46.560000
19731  2016-05-27 17:30:00          90       0  25.500000  46.500000
19732  2016-05-27 17:40:00         270      10  25.500000  46.596667
19733  2016-05-27 17:50:00         420      10  25.500000  46.990000
19734  2016-05-27 18:00:00         430      10  25.500000  46.600000

              T2       RH_2         T3       RH_3         T4  ...         T9  \
0      19.200000  44.790000  19.790000  44.730000  19.000000  ...  17.033333
1      19.200000  44.722500  19.790000  44.790000  19.000000  ...  17.066667
2      19.200000  44.626667  19.790000  44.933333  18.926667  ...  17.000000
3      19.200000  44.590000  19.790000  45.000000  18.890000  ...  17.000000
4      19.200000  44.530000  19.790000  45.000000  18.890000  ...  17.000000
...          ...        ...        ...        ...        ...  ...        ...
19730  25.890000  42.025714  27.200000  41.163333  24.700000  ...  23.200000
19731  25.754000  42.080000  27.133333  41.223333  24.700000  ...  23.200000
19732  25.628571  42.768571  27.050000  41.690000  24.700000  ...  23.200000
19733  25.414000  43.036000  26.890000  41.290000  24.700000  ...  23.200000
19734  25.264286  42.971429  26.823333  41.156667  24.700000  ...  23.200000

          RH_9      T_out  Press_mm_hg     RH_out  Windspeed  Visibility  \
0      45.5300   6.600000        733.5  92.000000   7.000000   63.000000
1      45.5600   6.483333        733.6  92.000000   6.666667   59.166667
2      45.5000   6.366667        733.7  92.000000   6.333333   55.333333
3      45.4000   6.250000        733.8  92.000000   6.000000   51.500000
4      45.4000   6.133333        733.9  92.000000   5.666667   47.666667
...        ...        ...          ...        ...        ...         ...
19730  46.7900  22.733333        755.2  55.666667   3.333333   23.666667
19731  46.7900  22.600000        755.2  56.000000   3.500000   24.500000
19732  46.7900  22.466667        755.2  56.333333   3.666667   25.333333
19733  46.8175  22.333333        755.2  56.666667   3.833333   26.166667
19734  46.8450  22.200000        755.2  57.000000   4.000000   27.000000

       Tdewpoint        rv1        rv2
0       5.300000  13.275433  13.275433
1       5.200000  18.606195  18.606195
2       5.100000  28.642668  28.642668
3       5.000000  45.410389  45.410389
4       4.900000  10.084097  10.084097
...          ...        ...        ...
19730  13.333333  43.096812  43.096812
19731  13.300000  49.282940  49.282940
19732  13.266667  29.199117  29.199117
19733  13.233333   6.322784   6.322784
19734  13.200000  34.118851  34.118851

[19735 rows x 29 columns]>

Checking for null features

In [5]:
df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

Dropping date and light features

In [60]:
data = df.drop(['date','lights'],axis=1)
data

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

Normalizing the dataset and splitting into train and test sample

In [61]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
# this is using MinMaxScaler to normalize the data 
scaler = MinMaxScaler()
normalizing_df = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
print(normalizing_df)

# defining our predictor and response value 
feature = normalizing_df.drop(columns =['Appliances'])
target = normalizing_df['Appliances']

X_train,X_test,y_train,y_test = train_test_split(feature,target, test_size=0.3, random_state=42)
linear_model = LinearRegression()

#fit the model to the training dataset
linear_model.fit(X_train,y_train)

#obtain predictions
predicted_values = linear_model.predict(X_test)
predicted_values

       Appliances        T1      RH_1        T2      RH_2        T3      RH_3  \
0        0.046729  0.327350  0.566187  0.225345  0.684038  0.215188  0.746066
1        0.046729  0.327350  0.541326  0.225345  0.682140  0.215188  0.748871
2        0.037383  0.327350  0.530502  0.225345  0.679445  0.215188  0.755569
3        0.037383  0.327350  0.524080  0.225345  0.678414  0.215188  0.758685
4        0.046729  0.327350  0.531419  0.225345  0.676727  0.215188  0.758685
...           ...       ...       ...       ...       ...       ...       ...
19730    0.084112  0.926786  0.537657  0.711655  0.606309  0.830841  0.579374
19731    0.074766  0.919747  0.536006  0.701769  0.607836  0.825302  0.582178
19732    0.242991  0.919747  0.538666  0.692651  0.627198  0.818378  0.603988
19733    0.383178  0.919747  0.549491  0.677054  0.634717  0.805085  0.585294
19734    0.392523  0.919747  0.538758  0.666171  0.632902  0.799546  0.579062

             T4      RH_4        T5  ...        T9      RH_9     T_out  \
0      0.351351  0.764262  0.175506  ...  0.223032  0.677290  0.372990
1      0.351351  0.782437  0.175506  ...  0.226500  0.678532  0.369239
2      0.344745  0.778062  0.175506  ...  0.219563  0.676049  0.365488
3      0.341441  0.770949  0.175506  ...  0.219563  0.671909  0.361736
4      0.341441  0.762697  0.178691  ...  0.219563  0.671909  0.357985
...         ...       ...       ...  ...       ...       ...       ...
19730  0.864865  0.765258  0.752031  ...  0.864724  0.729443  0.891747
19731  0.864865  0.765258  0.754897  ...  0.864724  0.729443  0.887460
19732  0.864865  0.771233  0.754897  ...  0.864724  0.729443  0.883173
19733  0.864865  0.773794  0.752031  ...  0.864724  0.730581  0.878885
19734  0.864865  0.781192  0.752031  ...  0.864724  0.731719  0.874598

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
0         0.097674  0.894737   0.500000    0.953846   0.538462  0.265449
1         0.100000  0.894737   0.476190    0.894872   0.533937  0.372083
2         0.102326  0.894737   0.452381    0.835897   0.529412  0.572848
3         0.104651  0.894737   0.428571    0.776923   0.524887  0.908261
4         0.106977  0.894737   0.404762    0.717949   0.520362  0.201611
...            ...       ...        ...         ...        ...       ...
19730     0.602326  0.416667   0.238095    0.348718   0.901961  0.861981
19731     0.602326  0.421053   0.250000    0.361538   0.900452  0.985726
19732     0.602326  0.425439   0.261905    0.374359   0.898944  0.583979
19733     0.602326  0.429825   0.273810    0.387179   0.897436  0.126371
19734     0.602326  0.434211   0.285714    0.400000   0.895928  0.682391

            rv2
0      0.265449
1      0.372083
2      0.572848
3      0.908261
4      0.201611
...         ...
19730  0.861981
19731  0.985726
19732  0.583979
19733  0.126371
19734  0.682391

[19735 rows x 27 columns]

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

MEAN SQUARED ERROR

In [63]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae,2)

0.05

RESIDUAL SUM OF SQUARE

In [64]:
import numpy as np
rss = np.sum(np.square(y_test - predicted_values))
round(rss,2)

45.35

ROOT MEAN SQUARE ERROR

In [79]:
from sklearn.metrics import mean_squared_error
rmse =np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse,3)

0.088

R_SQUARE

In [67]:
from sklearn.metrics import r2_score 
r2 = r2_score(y_test, predicted_values)
round(r2,2)

0.15

In [35]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [36]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [37]:
#comparing the effects of regularisation
def get_weights_df(linear_model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(linear_model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

linear_model_weights = get_weights_df(linear_model, X_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, X_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, X_train, 'Lasso_weight')

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')
final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.401134     -0.000000
1         T_out            -0.321860     -0.250765      0.000000
2            T2            -0.236178     -0.193880      0.000000
3            T9            -0.189941     -0.188584     -0.000000
4          RH_8            -0.157595     -0.156596     -0.000110
5        RH_out            -0.077671     -0.050541     -0.049557
6          RH_7            -0.044614     -0.046291     -0.000000
7          RH_9            -0.039800     -0.041701     -0.000000
8            T5            -0.015657     -0.020727     -0.000000
9            T1            -0.003281     -0.021549      0.000000
10          rv1             0.000770      0.000743     -0.000000
11          rv2             0.000770      0.000743     -0.000000
12  Press_mm_hg             0.006839      0.006516     -0.000000
13           T7             0.010319      0.010021     -0.000000
14   Visibility             0.012307      0.012032      0.000000
15         RH_5             0.016006      0.016176      0.000000
16         RH_4             0.026386      0.024168      0.000000
17           T4             0.028981      0.027006     -0.000000
18    Windspeed             0.029183      0.030463      0.002912
19         RH_6             0.038049      0.035023     -0.000000
20         RH_3             0.096048      0.094976      0.000000
21           T8             0.101995      0.100754      0.000000
22    Tdewpoint             0.117758      0.076668      0.000000
23           T6             0.236425      0.213316      0.000000
24           T3             0.290627      0.287408      0.000000
25         RH_1             0.553547      0.511932      0.017880

In [53]:
x = normalizing_df['T2'].values.reshape(-1,1)
y = normalizing_df['T6'].values.reshape(-1,1)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=42)
regressor = LinearRegression()
regressor.fit(x_train,y_train)
pred = regressor.predict(x_test)
r2 = r2_score(y_test, pred)
round(r2,2)

0.64

In [49]:
rcoefficient = pd.DataFrame(linear_model.coef_,feature.columns, columns=['Coefficient'])
round(rcoefficient,3)

             Coefficient
T1                -0.003
RH_1               0.554
T2                -0.236
RH_2              -0.457
T3                 0.291
RH_3               0.096
T4                 0.029
RH_4               0.026
T5                -0.016
RH_5               0.016
T6                 0.236
RH_6               0.038
T7                 0.010
RH_7              -0.045
T8                 0.102
RH_8              -0.158
T9                -0.190
RH_9              -0.040
T_out             -0.322
Press_mm_hg        0.007
RH_out            -0.078
Windspeed          0.029
Visibility         0.012
Tdewpoint          0.118
rv1                0.001
rv2                0.001

In [78]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(X_train, y_train)
pred = ridge_reg.predict(X_test)
from sklearn.metrics import mean_squared_error
rmse =np.sqrt(mean_squared_error(y_test, pred))
round(rmse,3)

0.088

In [73]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
lpred = lasso_reg.predict(X_test)
from sklearn.metrics import mean_squared_error
rmse =np.sqrt(mean_squared_error(y_test, lpred))
round(rmse,3)

0.094